### ISSUE TITLE
Images stored in the geopackage is in the Web Mercator (EPSG: 3857 )

### ISSUE THREAD

**Issue by mimikat** [Esri/raster2gpkg#1]
I am trying to make raster data in the geopackage format.  I found this page and made some geopackage files with images.  However, I have a few questions.  Could someone help me?

(Question 1):  Why are all the images stored in the geopackage in WGS84 Web mercator (EPSG: 3857 )?  The images do not have to be in this coordinate system, right? 
(Question 2):  Is there anyway I can store images in any other coordinate system?  When the image data in example.gpkg is opened in ArcGIS, the coordinate system of the image is not Web mercator (WPSG 3857).  HOw was the geopackage file created?  Was it created with the same tool posted on this page?

**Comment by lshipman** [comment]
Question 1: The standard does not require that all images be stored as Web Mercator.
Question 2: Currently the tool only stores images as Web Mercator. This will change at later versions. Can promise  when. Will update as soon as I have a better estimate. The GeoPackages can and should be created using the CreateSQLDatabase tool that is included in the toolbox. It is also available in Pro 1.1/1.2 and ArcGIS 10.4.

Lance Shipman
