### ISSUE TITLE
10.4 support?

### ISSUE THREAD

**Issue by achapkowski** [Esri/raster2gpkg#4]
Will there be 10.4 support for this tool? 
The dll provided will crash ArcGIS Desktop 10.4.

**Comment by achapkowski** [comment]
Further investigation for 10.4 installations, it appears the DLL provided will not work for 10.4, but the gdal dll in 10.4 will work as provided.  

I think part of the issue is that the script fails hard if the gpkg_scheme.xml isn't present.  A solution for this is to do a file check using os.path.isfile(path) and if it is not there throw an exception.

**Comment by lshipman** [comment]
The current tool requires that the gpkg_scheme.xml be present and the created GeoPackage tiled raster will be in WebMercator. We will be updating the tool in the next few weeks. 

If you are having problems at 10.4 turn off background geoprocessing.

**Comment by achapkowski** [comment]
@lshipman - thank you for this information!
